// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "11 Harold Road",
                            Name = "Ehsan",
                            Phone = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "22 Hastings Road",
                            Name = "Mahsa",
                            Phone = "321654"
                        },
                        new
                        {
                            Id = 3,
                            Address = "44 Denzil Avenue",
                            Name = "Poyan ",
                            Phone = "789987"
                        },
                        new
                        {
                            Id = 4,
                            Address = "10 Tessa Court",
                            Name = "Sam",
                            Phone = "456654"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9 Cindy Court",
                            Name = "Dash",
                            Phone = "987123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
